name: crossfire
description: A starting point for Dart libraries or applications.
 version: 1.0.0
 homepage: https://www.github.com/apptreesoftware/crossfire
# author: john <email@example.com>

environment:
  sdk: '>=1.23.0 <2.0.0'

dependencies:
  json_annotation: any

dev_dependencies:
  test: ^0.12.30
  build_runner: ^0.8.0
  json_serializable: any
