name: crossfire
description: Cross-platform firebase API
version: 1.0.0+1
homepage: https://www.github.com/apptreesoftware/crossfire
authors:
- John Ryan <john.p.ryan4@gmail.com>
- Matthew Smith <matthew.smith@apptree.cloud>

environment:
  sdk: '>=1.23.0 <2.0.0'

dependencies:
  json_annotation: ^0.2.0

dev_dependencies:
  test: ^0.12.30
  build_runner: ^0.8.0
  json_serializable: any
