name: crossfire_web
description: Cross-platform firebase API for browsers
version: 1.0.0
homepage: https://www.github.com/apptreesoftware/crossfire
authors:
- John Ryan <john.p.ryan4@gmail.com>
- Matthew Smith <matthew.smith@apptree.cloud>

environment:
  sdk: '>=1.23.0 <2.0.0'

dependencies:
  crossfire:
    path: /Users/john/code/projects/crossfire_mono/crossfire
  jsifier: any
  firebase: any

dev_dependencies:
  test: ^0.12.30
