name: crossfire_flutter
description: Cross-platform firebase API for Flutter
version: 1.0.0
homepage: https://www.github.com/apptreesoftware/crossfire
authors:
- John Ryan <john.p.ryan4@gmail.com>
- Matthew Smith <matthew.smith@apptree.cloud>

dependencies:
  flutter:
    sdk: flutter
  crossfire:
    path: /Users/john/code/projects/crossfire_mono/crossfire

  cloud_firestore: any
  # TODO: Make a PR
  # this branch allows switching between firebase apps at runtime
  firebase_auth:
    git:
      url: git://github.com/apptreesoftware/plugins
      path: packages/firebase_auth

  firebase_core: any
  firebase_storage: any
  firebase_database: any

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
